### ISSUE TITLE
plz add a "snap" feature 

### ISSUE THREAD

**Issue by tvvocold** [KennyShields/LightPaste#6]
plz add a "snap" feature .like https://github.com/pinterest/snappass
So users can send the passwd to their friends ( the link snap after they open it)

**Comment by KennyShields** [comment]
Sure, that should be pretty easy to add. Also, if I understand the "snap" system correctly, the paste would need to expire even if they don't open it, right?

**Comment by tvvocold** [comment]
yup,in another words, the link just could open 1 time,the second time, it disappear. just like snapchat.
(for user transfer passwd or something important)

**Comment by tvvocold** [comment]
@KennyShields Any update?

**Comment by KennyShields** [comment]
I've already worked on this a bit, though I took a break to take care of some other things. I should be able to finish this feature soon, perhaps withing the next few days or so.

**Comment by tvvocold** [comment]
Nice! Plz send me updates.

**Comment by KennyShields** [comment]
Snap functionality has been implemented in commit a347bde800fb98d719e84b3fc74b09e706d2cb76. Pastes that use the snap functionality will expire after 2 views.

**Comment by tvvocold** [comment]
Nice!
But how cloud i update it? or should i wait the capcha verison?

**Comment by KennyShields** [comment]
You'd need to update the schema in your database. If you are using MySQL you can use something like phpMyAdmin to make the changes. The update added 2 new columns to the pastes table: snap and hits, both of which are stored as integers.

**Comment by tvvocold** [comment]
OK, Cool!

**Comment by tvvocold** [comment]
check http://sebsauvage.net/paste/
