### ISSUE TITLE
Maybe add a asciipaint feature?

### ISSUE THREAD

**Issue by tvvocold** [KennyShields/LightPaste#7]
check this out! 
http://www.asciipaint.com/
and this http://p.fdzh.org/paste/ewK5QeKx

**Comment by tvvocold** [comment]
or this http://asciiflow.com/

**Comment by KennyShields** [comment]
Ascii paint is cool, though I don't think that it belongs in the official version of Light Paste.

**Comment by tvvocold** [comment]
OK,cool
